using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace PurchaseTrackerAPI.StaticStuff
{
    public class NotificationConstants
    {

        #region Notifications

        public enum NotificationsE
        {
            NEW_RATE_AND_QUOTA_DECLARED = 1,
            BOOKING_APPROVAL_REQUIRED = 2,
            BOOKING_APPROVED_BY_DIRECTORS = 3,
            BOOKING_CONFIRMED = 4,
            BOOKING_REJECTED_BY_DIRECTORS = 5,
            BOOKINGS_CLOSED = 6,
            TODAYS_STOCK_CONFIRMED = 7,
            TODAYS_STOCK_AS_PER_ACCOUNTANT = 8,
            BOOKING_ACCEPTED_BY_CNF = 9,
            BOOKING_REJECTED_BY_CNF = 10,
            LOADING_SLIP_CONFIRMATION_REQUIRED = 11,
            LOADING_SLIP_CONFIRMED = 12,
            LOADING_SLIP_CANCELLED = 13,
            VEHICLE_OUT_FOR_DELIVERY = 14,
            LOADING_QUOTA_DECLARED = 15,
            LOADING_STOPPED = 16,
            STRAIGHT_TO_BEND_TRANSFER_REQUEST = 17,
            INVOICE_APPROVAL_REQUIRED = 18,
            INVOICE_APPROVED_BY_DIRECTOR = 19,
            INVOICE_REJECTED_BY_DIRECTOR = 20,
            INVOICE_ACCEPTED_BY_DISTRIBUTOR = 21,
            INVOICE_REJECTED_BY_DISTRIBUTOR = 22,
            INVOICE_ACCEPTANCE_REQUIRED = 23,
            NEW_TRANSPORT_SLIP_GENERATE = 24,

            //Naresh Add
            PURCHASE_NEW_RATE_DECLARED = 501,//25,
            PURCHASE_BOOKINGS_CLOSED = 502,//28,
            PURCHASR_ENQUIRY_APPROVED_BY_DIRECTORS = 26,
            PURCHASR_ENQUIRY_REJECTED_BY_DIRECTORS = 27,
            PURCHASE_BOOKING_ACCEPTED_BY_CNF = 26,
            PURCHASE_BOOKING_REJECTED_BY_CNF = 27,
            PURCHASE_BOOKING_APPROVAL_REQUIRED = 29,
            PURCHASE_BOOKING_CONFIRMED = 503,//4,
            PURCHASE_VEHICLESPOT_ENTRY = 31,
            PURCHASE_VEHICLE_REPORTED = 504,//31,
            PURCHASE_VEHICLE_REQUESTED = 505,//32,
            SPOT_ENTRY_VEHICLE_REPORTED = 506,//33,
            // PURCHASE_VEHICLE_INSPECTED = 507,//34,

            PURCHASE_VEHICLE_SEND_FOR_INSPECTION = 507,//34,
            SEND_IN = 508,//35,
            WEIGHING_STAGE_COMPLETED = 509,//35,
            UNLOADING_STAGE_COMPLETED = 510,//35,
            ENQUIRY_APPROVED_BY_DIRECTOR = 511,
            ENQUIRY_REJECTED_BY_DIRECTOR = 512,//35,
            ENQUIRY_PENDING_FOR_ACCEPTANCE_BY_DIRECTOR = 513,
            ENQUIRY_PENDING_FOR_ACCEPTANCE_BY_PM = 514,
            PURCHASE_VEHICLE_SAMPLEFLAG_BY_OUTSIDE_INSPECTOR = 51,//31,
            PURCHASE_WEIGHING_DONE_CALLCULATE_RECOVERY = 52,//31,
            UNLOADING_COMPLETED = 515,//35,
            GRADING_COMPLETED = 516,//35,
            CORRECTION_COMPLETED = 517,//35,

            VEHICLE_SCHEDULE_PENDING_FOR_APPROVAL = 518,
            VEHICLE_SCHEDULE_APPROVED = 519,
            VEHICLE_SCHEDULE_REJECTED = 520,
            PURCHASE_VEHICLE_ASSIGN_TO_SUPERVISOR = 521,//32,
            PURCHASE_VEHICLE_SEND_FOR_VERIFICATION = 524,
            RECOVERY_COMPLETED = 525,
            GRADERS_APPROVAL_COMPLETED = 526,

            BOOKING_DELETED = 527,

            VEHICLE_SCHEDULE_PENDING_FOR_YARD_MANAGER = 528,
            PURCHASE_VEHICLE_ASSIGN_TO_GRADER = 529,
            PURCHASE_VEHICLE_ASSIGN_TO_ENGINEER = 530,

            VEHICLE_SCHEDULE_PENDING_FOR_WT_RATE_APPROVAL = 531,

            VEHICLE_SCHEDULE_APPROVED_FOR_WT_RATE = 532,

            VEHICLE_SCHEDULE_REJECTED_FOR_WT_RATE = 533,

            VEH_APPROVAL_PENDING_FOR_SPOT_VEH_QTY_GREATER_THAN_PEND_SAUDA_QTY = 534,

            SPOT_VEH_QTY_GREATER_THAN_PEND_SAUDA_QTY_APPROVED = 535,

            SPOT_VEH_QTY_GREATER_THAN_PEND_SAUDA_QTY_REJECTED = 536,

            SAUDA_CLOSURE_REQ_PENDING_FOR_APPROVAL = 537,
            SAUDA_CLOSURE_REQ_APPROVED = 538,
            SAUDA_CLOSURE_REQ_REJECTED = 539,
            AUTO_CREATED_SAUDA_FOR_SPOT_VEHICLE = 540,
            PARTY_NET_WT_GREATER_THAN_ACTUAL_WT = 541,
            COMMERCIAL_DTLS_NOT_FOUND_WHILE_CORRECTION = 542,

        }

        #endregion

        public enum NotificationTypeE
        {
            ALERT = 1,
            EMAIL = 2,
            SMS = 3
        }
    }
}
